services:
- type: web
  name: g-site-backend
  env: python
  buildCommand: "pip install -r requirements.txt"
  startCommand: "PYTHONPATH=. gunicorn main:app"
  plan: free # Usa il piano gratuito per default
  # Render assegna automaticamente una porta, ma Gunicorn ascolta su 8000 per default.
  # Non è necessario specificare la porta 5000 o 8000 qui, Render la gestisce.
